Window docs fixes
import random causes failure:

Python 2 error:

	WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly

PYTHONHASHSEED=1
Python 3 warning, then silent failure to build CLI docs:

	Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python