Windows fixes for documentation generation
- Update the 'make_docs' shell script to work on Windows (via Git BASH).
- Added workarounds for some weird "random" module import/startup issues.
  Upgrading to the latest 2.x and 3.x release didn't help.  Win10 only?
- Support proper environmental variable data types (bytes vs unicode) for
  make_dyn_docs to resolve some Python 2 vs 3 issues.  (Possibly also OS
  specific, pretty sure I had this working on both PY2/3 on the Mac)
- Minor updates to cheatsheet page.
- Disable 'detect-aws-credentials' pre-commit check to avoid extra dependencies.

Notes about 'random' module errors:

Python 2 error:

    WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly

Workaround:   try/except around 'import random'

Python 3 warning:  (Then it silently failed to output CLI docs)

    Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python

Workaround:  PYTHONHASHSEED=1